// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7IVixYYY0g0IGCBXhokr-S3YvRSadPG0',
    appId: '1:200370913890:web:1156084694290aedea073b',
    messagingSenderId: '200370913890',
    projectId: 'flutterapp-4ae24',
    authDomain: 'flutterapp-4ae24.firebaseapp.com',
    storageBucket: 'flutterapp-4ae24.appspot.com',
    measurementId: 'G-W3ZWV575F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3JK3POCTy5JJI3haCz2yycWeLeJvYxt0',
    appId: '1:200370913890:android:f720cfe22500a9e2ea073b',
    messagingSenderId: '200370913890',
    projectId: 'flutterapp-4ae24',
    storageBucket: 'flutterapp-4ae24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCDVvlm0pgftUdxHhGvwaIuR4sFSr0qw',
    appId: '1:200370913890:ios:248c67ff73ae66d2ea073b',
    messagingSenderId: '200370913890',
    projectId: 'flutterapp-4ae24',
    storageBucket: 'flutterapp-4ae24.appspot.com',
    iosClientId: '200370913890-2ibi6abihpkfoikktmsvnsk636h92rch.apps.googleusercontent.com',
    iosBundleId: 'com.example.jplaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCDVvlm0pgftUdxHhGvwaIuR4sFSr0qw',
    appId: '1:200370913890:ios:248c67ff73ae66d2ea073b',
    messagingSenderId: '200370913890',
    projectId: 'flutterapp-4ae24',
    storageBucket: 'flutterapp-4ae24.appspot.com',
    iosClientId: '200370913890-2ibi6abihpkfoikktmsvnsk636h92rch.apps.googleusercontent.com',
    iosBundleId: 'com.example.jplaProject',
  );
}
